version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: meu_app_development
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: meu_app_development
      SECRET_KEY_BASE: e962bd4369b294c826ef30394748bc9a7263d2f80d90b74615a6e2c60abb7fd6e3afe0560a8f922ad88dfd8ddd8d140b25a310f93bdb124f117f3e653af279a8

volumes:
  mysql-data: